version: 2
jobs:
  build:
    working_directory: ~/midje-tabular-formatter
    docker:
    - image: circleci/clojure:lein-2.9.1
    steps:
    - checkout
    - restore_cache:
        key: midje-tabular-formatter-{{ checksum "project.clj" }}
    - run:
        name: Run tests
        command: |
          lein midje :print-facts
    - save_cache:
        paths:
        - ~/.m2
        key: midje-tabular-formatter-{{ checksum "project.clj" }}
